export enum AuditAction {
  // Document actions
  CREATE_DOCUMENT = "CREATE_DOCUMENT",
  VIEW_DOCUMENT = "VIEW_DOCUMENT",
  UPDATE_DOCUMENT = "UPDATE_DOCUMENT",
  DELETE_DOCUMENT = "DELETE_DOCUMENT",
  SIGN_DOCUMENT = "SIGN_DOCUMENT",
  REJECT_DOCUMENT = "REJECT_DOCUMENT",

  // Signature
  CREATE_SIGNATURE = "CREATE_SIGNATURE",
  REMOVE_SIGNATURE = "REMOVE_SIGNATURE",
  RESTORE_SIGNATURE = "RESTORE_SIGNATURE",

  // Auth actions
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  LOGOUT = "LOGOUT",

  // User actions
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_RESTORED = "USER_RESTORED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET = "PASSWORD_RESET",

  // Sector actions
  SECTOR_CREATED = "SECTOR_CREATED",
  SECTOR_UPDATED = "SECTOR_UPDATED",
  SECTOR_REMOVED = "SECTOR_REMOVED",
  SECTOR_RESTORED = "SECTOR_RESTORED",

  PAID_INSTALLMENT = "PAID_INSTALLMENT",

  // System actions
  SYSTEM_ERROR = "SYSTEM_ERROR",
}
