version: "3.8"

services:
  # Serviço para a aplicação NestJS
  backend:
    image: igorgois/signature-backend:latest
    container_name: signature-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3440
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: signatures
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "3440:3440"
