export enum DocumentType {
  ADVANCE_PAYMENT = "ADVANCE_PAYMENT", // ADIANTAMENTOS
  BANK_SLIP = "BANK_SLIP", // BOLETO
  CHECK = "CHECK", // CHEQUE
  CREDIT_CARD = "CREDIT_CARD", // CARTÃO DE CRÉDITO
  POST_DATED_CHECK = "POST_DATED_CHECK", // CHEQUE PRÉ DATADO
  TRADE_BILL = "TRADE_BILL", // DUPLICATA
  LOAN = "LOAN", // EMPRÉSTIMO
  PETTY_CASH = "PETTY_CASH", // FUNDO DE CAIXA
  VACATION_PAY = "VACATION_PAY", // FÉRIAS
  SEVERANCE_FUND = "SEVERANCE_FUND", // FGTS
  PAYROLL = "PAYROLL", // FOLHA
  SOCIAL_SECURITY = "SOCIAL_SECURITY", // INSS
  TAXES = "TAXES", // IMPOSTOS
  CREDIT_NOTE = "CREDIT_NOTE", // NOTA DE CRÉDITO
  SUPPLIER_RETURN_NOTE = "SUPPLIER_RETURN_NOTE", // NOTA DE DEVOLUÇÃO FORNECEDOR
  ADVANCE_PAYMENT_TO_SUPPLIER = "ADVANCE_PAYMENT_TO_SUPPLIER", // PAGAMENTO ANTECIPADO
  BRADESCO_HEALTH_PLAN = "BRADESCO_HEALTH_PLAN", // PLANO DE SAÚDE BRADESCO
  FORECAST = "FORECAST", // PREVISÃO
  ADVANCE_RECEIPT = "ADVANCE_RECEIPT", // RECEBIMENTO ANTECIPADO
  RECEIPT = "RECEIPT", // RECIBO
  TERMINATION = "TERMINATION", // RESCISÃO
  HEALTH_PLAN = "HEALTH_PLAN", // PLANO DE SAÚDE
  TRIBUTES = "TRIBUTES", // TRIBUTOS
  FEES = "FEES", // TAXAS
  GENERAL = "GENERAL", // GERAL
}

export enum DocumentStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  DRAFT = "DRAFT",
  REJECTED = "REJECTED",
}

export enum DocumentNature {
  // Despesas com Pessoal
  SALARIES = "SALARIES",
  SOCIAL_SECURITY = "SOCIAL_SECURITY", // INSS
  SEVERANCE_FUND = "SEVERANCE_FUND", // FGTS
  VACATION = "VACATION",
  THIRTEENTH_SALARY = "THIRTEENTH_SALARY", // 13 SALARIO
  TRANSPORT_VOUCHERS = "TRANSPORT_VOUCHERS", // V. TRANSPORTES / VALE TRANSPORTE
  TRAINING = "TRAINING",
  MEDICATIONS = "MEDICATIONS",
  HEALTH_DENTAL_PLAN = "HEALTH_DENTAL_PLAN",
  PERFORMANCE_BONUS = "PERFORMANCE_BONUS", // PREMIACAO S/ META E AVALIACAO
  OUTSOURCED_SERVICES = "OUTSOURCED_SERVICES",
  GV_GRATIFICATION = "GV_GRATIFICATION", // GRATIFICACAO GV (mantido como está por ser um acrônimo)
  EXTRA_GRATIFICATION = "EXTRA_GRATIFICATION",
  VARIABLE_REMUNERATION_BONUS = "VARIABLE_REMUNERATION_BONUS", // PREMIO RV ( REMUNERACAO VARIAVEL )
  TEMPORARY_SUPPLIER_SERVICES = "TEMPORARY_SUPPLIER_SERVICES",
  COOPERATIVE_SERVICES = "COOPERATIVE_SERVICES",
  OVERTIME = "OVERTIME",
  ADMISSION_TERMINATION_EXPENSES = "ADMISSION_TERMINATION_EXPENSES",
  INTERNAL_EVENTS = "INTERNAL_EVENTS",
  INDEMNITIES = "INDEMNITIES",
  UNIFORMS = "UNIFORMS",
  PRO_LABORE = "PRO_LABORE",
  INTERNSHIP_GRANT = "INTERNSHIP_GRANT", // BOLSA DE ESTAGIO
  UNHEALTHINESS_ALLOWANCE = "UNHEALTHINESS_ALLOWANCE", // INSALUBRIDADE
  OCCUPATIONAL_HEALTH_SAFETY = "OCCUPATIONAL_HEALTH_SAFETY", // MEDICINA E SEGURANCA DO TRABALHO
  EMPLOYEE_LIFE_INSURANCE = "EMPLOYEE_LIFE_INSURANCE",
  PROFIT_SHARING = "PROFIT_SHARING", // PARTICIPACAO NOS LUCROS E RESULTADOS

  // Despesas de Marketing e Publicidade
  ADVERTISING_PUBLICITY = "ADVERTISING_PUBLICITY",
  PROMOTIONAL_GIFTS = "PROMOTIONAL_GIFTS",
  PARTICIPATION_IN_FAIRS_EVENTS = "PARTICIPATION_IN_FAIRS_EVENTS",
  DONATIONS_CONTRIBUTIONS = "DONATIONS_CONTRIBUTIONS",
  MARKET_RESEARCH = "MARKET_RESEARCH",
  MARKETING_CONSULTANCY = "MARKETING_CONSULTANCY",
  DIRECT_MARKETING = "DIRECT_MARKETING",
  BONUSES = "BONUSES", // BONIFICACAO
  COMMISSIONS_PAID_TO_THIRD_PARTIES = "COMMISSIONS_PAID_TO_THIRD_PARTIES",

  // Despesas Operacionais e de Manutenção
  TEMPORARY_REDISTRIBUTION_SERVICES = "TEMPORARY_REDISTRIBUTION_SERVICES",
  OFFICE_SUPPLIES = "OFFICE_SUPPLIES",
  CLEANING_PANTRY_SUPPLIES = "CLEANING_PANTRY_SUPPLIES",
  FUELS_LUBRICANTS = "FUELS_LUBRICANTS",
  PARTS_TIRES_MAINTENANCE = "PARTS_TIRES_MAINTENANCE",
  REGISTRATION_INSURANCE_FINES_FEES = "REGISTRATION_INSURANCE_FINES_FEES", // EMPLACAMENTO / SEGUROS / MULTAS / TAXAS
  LEASING = "LEASING", // ARRENDAMENTO MERCANTIL - LEASING
  VEHICLE_RENTAL = "VEHICLE_RENTAL",
  VEHICLE_INSURANCE_EXPENSES = "VEHICLE_INSURANCE_EXPENSES",
  TELEPHONE_EXPENSES = "TELEPHONE_EXPENSES",
  ELECTRICITY = "ELECTRICITY",
  POSTAL_SERVICES = "POSTAL_SERVICES",
  WATER_SEWAGE = "WATER_SEWAGE",
  BUILDING_INSTALLATION_EQUIPMENT_MAINTENANCE_REPAIR = "BUILDING_INSTALLATION_EQUIPMENT_MAINTENANCE_REPAIR",
  IT_MAINTENANCE_SERVICES = "IT_MAINTENANCE_SERVICES", // SERV. MANUT. INFORMATICA
  VIGILANCE_GENERAL_SERVICES = "VIGILANCE_GENERAL_SERVICES", // VIGILANCIA E SERVICOS GERAIS

  // Despesas com Consultorias e Serviços Profissionais
  LEGAL_CONSULTANCY = "LEGAL_CONSULTANCY",
  ACCOUNTING_CONSULTANCY = "ACCOUNTING_CONSULTANCY",
  HR_CONSULTANCY = "HR_CONSULTANCY",
  BUSINESS_CONSULTANCY = "BUSINESS_CONSULTANCY",
  TECHNICAL_CONSULTANCY = "TECHNICAL_CONSULTANCY",
  ADVERTISEMENTS_PUBLICATIONS = "ADVERTISEMENTS_PUBLICATIONS",
  RENTS_CONDOMINIUM_FEES = "RENTS_CONDOMINIUM_FEES",
  NOTARY_JUDICIAL_FEES = "NOTARY_JUDICIAL_FEES",
  PROPERTY_INSURANCE = "PROPERTY_INSURANCE",
  NEWSPAPER_MAGAZINE_INTERNET_SUBSCRIPTIONS = "NEWSPAPER_MAGAZINE_INTERNET_SUBSCRIPTIONS",
  ASSOCIATIONS_CREDIT_BUREAU_FEES = "ASSOCIATIONS_CREDIT_BUREAU_FEES", // ASSOCIACOES / SPC / SERASA
  SNACKS_MEALS = "SNACKS_MEALS",
  CONSUMABLE_MATERIALS = "CONSUMABLE_MATERIALS",
  EXTERNAL_COLLECTION_SERVICES = "EXTERNAL_COLLECTION_SERVICES",
  LABOR_CONSULTANCY = "LABOR_CONSULTANCY",
  FINANCIAL_CREDIT_CONSULTANCY = "FINANCIAL_CREDIT_CONSULTANCY",
  CORPORATE_CONSULTANCY = "CORPORATE_CONSULTANCY", // ASSESSORIA SOCIETARIA

  // Despesas com Impostos e Taxas
  CORPORATE_INCOME_TAX = "CORPORATE_INCOME_TAX", // IMPOSTO DE RENDA PESSOA JURIDICA
  SOCIAL_CONTRIBUTION_ON_PROFIT = "SOCIAL_CONTRIBUTION_ON_PROFIT", // CONTRIBUICAO SOCIAL S/ LUCRO
  DIVERSE_FEES = "DIVERSE_FEES",
  ICMS_CREDIT_REVERSAL = "ICMS_CREDIT_REVERSAL",
  OTHER_STATE_TAXES = "OTHER_STATE_TAXES",
  OTHER_FEDERAL_TAXES = "OTHER_FEDERAL_TAXES",
  OTHER_MUNICIPAL_TAXES = "OTHER_MUNICIPAL_TAXES",
  TAX_FINES = "TAX_FINES", // MULTAS FISCAIS
  TRAFFIC_FINES = "TRAFFIC_FINES", // MULTAS DE TRANSITO

  // Outras Despesas
  TRAVEL_ACCOMMODATION = "TRAVEL_ACCOMMODATION",
  CUSTOMER_COMPENSATION = "CUSTOMER_COMPENSATION",
  PRODUCT_ANALYSIS = "PRODUCT_ANALYSIS",
  RISK_FUND = "RISK_FUND",
  VEHICLE_FINANCING_CDC = "VEHICLE_FINANCING_CDC",
  OTHER_LOSSES = "OTHER_LOSSES",
  IMPLEMENTATION_PRE_OPERATIONAL_EXPENSES = "IMPLEMENTATION_PRE_OPERATIONAL_EXPENSES", // GASTOS DE IMPLANTACAO E PRE OPERACIONAIS
  PRODUCT_RESEARCH_DEVELOPMENT_EXPENSES = "PRODUCT_RESEARCH_DEVELOPMENT_EXPENSES", // GASTOS C/ PESQUISA E DESENVOLV. PRODUTOS
  NON_DEDUCTIBLE_EXPENSES = "NON_DEDUCTIBLE_EXPENSES",
  UNCOLLECTIBLE_CREDIT_EXPENSE = "UNCOLLECTIBLE_CREDIT_EXPENSE", // DESPESA COM CREDITOS INCOBRAVEIS
  OTHER_EXPENSES = "OTHER_EXPENSES",
  TRAVEL_ALLOWANCES = "TRAVEL_ALLOWANCES", // DIÁRIAS PARA VIAGEM

  // Ativos / Investimentos
  INSTALLATIONS = "INSTALLATIONS",
  TOOLS = "TOOLS",
  VEHICLES = "VEHICLES",
  MOTORCYCLE = "MOTORCYCLE",
  FURNITURE_UTENSILS = "FURNITURE_UTENSILS",
  MACHINERY_EQUIPMENT = "MACHINERY_EQUIPMENT",
  DATA_PROCESSING_SYSTEM_HARDWARE = "DATA_PROCESSING_SYSTEM_HARDWARE",
  DATA_PROCESSING_SYSTEM_SOFTWARE = "DATA_PROCESSING_SYSTEM_SOFTWARE",
  TRADEMARKS_PATENTS = "TRADEMARKS_PATENTS",
  REAL_ESTATE_BUILDINGS = "REAL_ESTATE_BUILDINGS",
  IMPROVEMENTS_ON_THIRD_PARTY_PROPERTIES = "IMPROVEMENTS_ON_THIRD_PARTY_PROPERTIES",
  COMPUTERS_PERIPHERALS = "COMPUTERS_PERIPHERALS",

  // Despesas e Receitas de Frete/Serviços a Clientes
  FREIGHT_CARGO_FOR_CLIENTS = "FREIGHT_CARGO_FOR_CLIENTS",
  CLIENT_INSURANCE = "CLIENT_INSURANCE",
  SERVICES_PROVIDED_TO_CLIENTS = "SERVICES_PROVIDED_TO_CLIENTS",
  INDIVIDUAL_FREIGHT = "INDIVIDUAL_FREIGHT",
  CORPORATE_FREIGHT = "CORPORATE_FREIGHT",
  LOADING_UNLOADING_SERVICES_CLIENTS = "LOADING_UNLOADING_SERVICES_CLIENTS",
  LOADING_UNLOADING_SERVICES_PURCHASES = "LOADING_UNLOADING_SERVICES_PURCHASES",

  // Receitas
  RECOVERY_OF_UNCOLLECTIBLE_CREDITS = "RECOVERY_OF_UNCOLLECTIBLE_CREDITS", // RECUPERACAO DE CREDITOS INCOBRAVEIS
  EXPENSE_RECOVERY = "EXPENSE_RECOVERY",
  COMMISSIONS_RECEIVED = "COMMISSIONS_RECEIVED",
  RENTAL_INCOME = "RENTAL_INCOME",
  OTHER_REVENUES = "OTHER_REVENUES",
}

export interface IDocument {
  id: number;
  title: string;
  description: string | null;
  tipoDocumento: DocumentType;
  fileId: number;
  natureza: string;
  status: DocumentStatus;
  valor: number | null;
  dataVencimento: Date | null;
  observacoes: string | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date;
  ownerId: number | null;
  fornecedorId: number | null;
}
